class K{
	public static void main(String[] args){
		//case 1
        /* try{
               int[] x={11,12,13};
			   System.out.println(x[3]);
		 }catch(IndexOutOfBoundsException e){
               System.out.println(e);
		 }catch(ArrayIndexOutOfBoundsException e){
                System.out.println(e);
		 }*/

		 //case 2
       /*  try{
               int[] x={11,12,13};
			   System.out.println(x[3]);
		 }catch(ArrayIndexOutOfBoundsException e){
               System.out.println(e);
		 }catch(IndexOutOfBoundsException e){
                System.out.println(e);
		 }*/
	}
}
/*there is no problem with the sequence of catch block but when there is more than one catch block and there exception class have
parent child relationship than always write the child first than it gives u error*/